#!/bin/sh

OPTION=FRAMEBUFFER
PREREQ="framebuffer console_setup brltty"

prereqs()
{
        echo "$PREREQ"
}

case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

SPLASH=false

for x in $(cat /proc/cmdline); do
        case $x in
        splash*)
                SPLASH=true
                ;;
        nosplash*)
                SPLASH=false
                ;;
        esac
done

if [ $SPLASH = "true" ]; then
	printf '\033[?25l' > /dev/tty7
	/sbin/plymouthd --mode=boot --pid-file=/dev/.initramfs/plymouth.pid
	/bin/plymouth --show-splash
fi
